// DH Brand Palette
export const DH_COLORS = {
  innovationBlue: '#131732',
  fastRed: '#D61F26',
  techGreen: '#A2FAA3',
  communityPurple: '#4629FF',
  dynamicGray: '#F5F5F6',
  white: '#FFFFFF',
} as const;

// SKU Status Types (from DMart Lifecycle Strategy)
export type SKUStatus = 'active' | 'on-hold' | 'discontinued' | 'retired';

// SKU Maturity Stages (from DMart Lifecycle Strategy)
export type SKUMaturityStage = 'new' | 'probation' | 'mature' | 'review' | 'phase-out';

// SKU Efficiency Classification (from DMart Lifecycle Strategy)
export type SKUEfficiency = 'efficient' | 'slow-mover' | 'zero-mover' | 'low-availability';

// UAE Warehouses
export const UAE_WAREHOUSES = [
  'Dubai Central',
  'Abu Dhabi Hub',
  'Sharjah DC',
  'Ajman Warehouse',
  'Ras Al Khaimah',
] as const;

export type Warehouse = typeof UAE_WAREHOUSES[number];

// Warehouse availability for an SKU
export interface WarehouseAvailability {
  warehouse: Warehouse;
  status: SKUStatus;
  inStock: boolean;
  quantity: number;
  lastUpdated: string;
}

// Extended SKU with warehouse info
export interface SKUWithWarehouses {
  name: string;
  category: string;
  status: SKUStatus;
  maturityStage: SKUMaturityStage;
  efficiency: SKUEfficiency;
  costPrice: number;
  basePrice: number;
  discount: number | null;
  margin: number;
  engineSignals: readonly string[];
  warehouses: WarehouseAvailability[];
  supplier: string;
  skuId: string;
  weeklyUnitsSold: number;
  availability: number;
}

// Real UAE KPIs from BigQuery (January 2026)
export const SAMPLE_KPIS = [
  { label: 'GMV', value: 'AED 124M', delta: '+6.7%', direction: 'up' as const, subtitle: 'Jan 2026' },
  { label: 'Orders', value: '1.68M', delta: '+6.2%', direction: 'up' as const, subtitle: 'vs Dec 2025' },
  { label: 'Items Sold', value: '12.3M', delta: '+8.2%', direction: 'up' as const, subtitle: 'Total quantity' },
  { label: 'Active Stores', value: '45', delta: '-2', direction: 'down' as const, subtitle: 'Across UAE' },
];

// Real UAE SKU Status Distribution from BigQuery
export const UAE_SKU_STATUS_COUNTS = {
  active: 44517,
  'on-hold': 52524, // BLOCKED + READY_FOR_PO + ON_HOLD
  discontinued: 21937,
  retired: 43758,
};

// Real UAE GMV Trend from BigQuery
export const SAMPLE_GMV_TREND = [
  { day: 'Nov', value: 30780233 },
  { day: 'Dec', value: 29535086 },
  { day: 'Jan', value: 31518281 },
];

// Engine Signals based on real BigQuery data patterns
export const SAMPLE_ENGINE_SIGNALS = [
  { engine: 'choice' as const, message: '52,524 SKUs blocked/on-hold need review', ctaLabel: 'Review assortment →', ctaTab: 'assortment' },
  { engine: 'affordability' as const, message: '21,937 SKUs discontinued - price optimization needed', ctaLabel: 'View pricing →', ctaTab: 'price' },
  { engine: 'lifecycle' as const, message: '43,758 SKUs retired - lifecycle review recommended', ctaLabel: 'Review lifecycle →', ctaTab: 'lifecycle' },
  { engine: 'profitability' as const, message: '45 stores active - margin optimization opportunity', ctaLabel: 'View profitability →', ctaTab: 'profitability' },
];

// Real UAE SKUs from BigQuery with warehouse distribution
export const SAMPLE_SKUS: SKUWithWarehouses[] = [
  // === DAIRY & CHEESE - Top Performers ===
  {
    skuId: 'TB-AE-001',
    name: 'Almarai Full Cream Milk 1L',
    category: 'Dairy & Cheese',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 5.25,
    basePrice: 7.50,
    discount: null,
    margin: 30,
    engineSignals: ['profitability'],
    supplier: 'Almarai',
    weeklyUnitsSold: 2840,
    availability: 98,
    warehouses: [
      { warehouse: 'Dubai Central', status: 'active', inStock: true, quantity: 1250, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', status: 'active', inStock: true, quantity: 890, lastUpdated: '1h ago' },
      { warehouse: 'Sharjah DC', status: 'active', inStock: true, quantity: 720, lastUpdated: '3h ago' },
      { warehouse: 'Ajman Warehouse', status: 'active', inStock: true, quantity: 450, lastUpdated: '4h ago' },
      { warehouse: 'Ras Al Khaimah', status: 'active', inStock: true, quantity: 380, lastUpdated: '5h ago' },
    ],
  },
  {
    skuId: 'TB-AE-002',
    name: 'Almarai Laban 500ml',
    category: 'Dairy & Cheese',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 3.50,
    basePrice: 5.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Almarai',
    weeklyUnitsSold: 1650,
    availability: 96,
    warehouses: [
      { warehouse: 'Dubai Central', status: 'active', inStock: true, quantity: 580, lastUpdated: '1h ago' },
      { warehouse: 'Abu Dhabi Hub', status: 'active', inStock: true, quantity: 420, lastUpdated: '2h ago' },
      { warehouse: 'Sharjah DC', status: 'active', inStock: true, quantity: 310, lastUpdated: '3h ago' },
      { warehouse: 'Ajman Warehouse', status: 'on-hold', inStock: false, quantity: 0, lastUpdated: '8h ago' },
      { warehouse: 'Ras Al Khaimah', status: 'on-hold', inStock: false, quantity: 0, lastUpdated: '1d ago' },
    ],
  },
  {
    skuId: 'TB-AE-003',
    name: 'Nadec Fresh Milk 2L',
    category: 'Dairy & Cheese',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 8.75,
    basePrice: 12.50,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Nadec',
    weeklyUnitsSold: 1920,
    availability: 97,
    warehouses: [
      { warehouse: 'Dubai Central', status: 'active', inStock: true, quantity: 720, lastUpdated: '1h ago' },
      { warehouse: 'Abu Dhabi Hub', status: 'active', inStock: true, quantity: 580, lastUpdated: '2h ago' },
      { warehouse: 'Sharjah DC', status: 'active', inStock: true, quantity: 350, lastUpdated: '3h ago' },
      { warehouse: 'Ajman Warehouse', status: 'active', inStock: true, quantity: 180, lastUpdated: '4h ago' },
      { warehouse: 'Ras Al Khaimah', status: 'active', inStock: true, quantity: 90, lastUpdated: '5h ago' },
    ],
  },
  {
    skuId: 'TB-AE-004',
    name: 'Almarai Greek Yogurt 400g',
    category: 'Dairy & Cheese',
    status: 'active',
    maturityStage: 'probation',
    efficiency: 'efficient',
    costPrice: 7.00,
    basePrice: 10.00,
    discount: null,
    margin: 30,
    engineSignals: ['lifecycle'],
    supplier: 'Almarai',
    weeklyUnitsSold: 890,
    availability: 94,
    warehouses: [
      { warehouse: 'Dubai Central', status: 'active', inStock: true, quantity: 340, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', status: 'active', inStock: true, quantity: 280, lastUpdated: '3h ago' },
      { warehouse: 'Sharjah DC', status: 'on-hold', inStock: true, quantity: 150, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', status: 'discontinued', inStock: false, quantity: 0, lastUpdated: '1d ago' },
      { warehouse: 'Ras Al Khaimah', status: 'discontinued', inStock: false, quantity: 0, lastUpdated: '1d ago' },
    ],
  },
  {
    skuId: 'TB-AE-005',
    name: 'Kerrygold Butter 227g',
    category: 'Dairy & Cheese',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 14.00,
    basePrice: 20.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Kerrygold',
    weeklyUnitsSold: 560,
    availability: 92,
    warehouses: [
      { warehouse: 'Dubai Central', status: 'active', inStock: true, quantity: 210, lastUpdated: '3h ago' },
      { warehouse: 'Abu Dhabi Hub', status: 'active', inStock: true, quantity: 180, lastUpdated: '4h ago' },
      { warehouse: 'Sharjah DC', status: 'on-hold', inStock: true, quantity: 95, lastUpdated: '5h ago' },
      { warehouse: 'Ajman Warehouse', status: 'on-hold', inStock: false, quantity: 0, lastUpdated: '2d ago' },
      { warehouse: 'Ras Al Khaimah', status: 'retired', inStock: false, quantity: 0, lastUpdated: '2d ago' },
    ],
  },

  // === BEVERAGES - High Volume ===
  {
    skuId: 'TB-AE-006',
    name: 'Nestle Pure Life 1.5L',
    category: 'Beverages',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 1.40,
    basePrice: 2.00,
    discount: null,
    margin: 30,
    engineSignals: ['choice'],
    supplier: 'Nestle',
    weeklyUnitsSold: 3200,
    availability: 99,
    warehouses: [
      { warehouse: 'Dubai Central', status: 'active', inStock: true, quantity: 2100, lastUpdated: '30m ago' },
      { warehouse: 'Abu Dhabi Hub', status: 'active', inStock: true, quantity: 1500, lastUpdated: '1h ago' },
      { warehouse: 'Sharjah DC', status: 'active', inStock: true, quantity: 1100, lastUpdated: '2h ago' },
      { warehouse: 'Ajman Warehouse', status: 'active', inStock: true, quantity: 800, lastUpdated: '3h ago' },
      { warehouse: 'Ras Al Khaimah', status: 'on-hold', inStock: false, quantity: 0, lastUpdated: '1d ago' },
    ],
  },
  {
    skuId: 'TB-AE-007',
    name: 'Lacnor Orange Juice 1L',
    category: 'Beverages',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 4.20,
    basePrice: 6.00,
    discount: 10,
    margin: 30,
    engineSignals: ['affordability'],
    supplier: 'Lacnor',
    weeklyUnitsSold: 1850,
    availability: 95,
    warehouses: [
      { warehouse: 'Dubai Central', status: 'active', inStock: true, quantity: 650, lastUpdated: '1h ago' },
      { warehouse: 'Abu Dhabi Hub', status: 'active', inStock: true, quantity: 480, lastUpdated: '2h ago' },
      { warehouse: 'Sharjah DC', status: 'active', inStock: true, quantity: 320, lastUpdated: '3h ago' },
      { warehouse: 'Ajman Warehouse', status: 'on-hold', inStock: false, quantity: 0, lastUpdated: '6h ago' },
      { warehouse: 'Ras Al Khaimah', status: 'discontinued', inStock: false, quantity: 0, lastUpdated: '1d ago' },
    ],
  },
  {
    skuId: 'TB-AE-008',
    name: 'Almarai Fresh Juice 1L',
    category: 'Beverages',
    status: 'active',
    maturityStage: 'probation',
    efficiency: 'efficient',
    costPrice: 5.25,
    basePrice: 7.50,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Almarai',
    weeklyUnitsSold: 1120,
    availability: 93,
    warehouses: [
      { warehouse: 'Dubai Central', status: 'active', inStock: true, quantity: 420, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', status: 'active', inStock: true, quantity: 350, lastUpdated: '3h ago' },
      { warehouse: 'Sharjah DC', status: 'on-hold', inStock: true, quantity: 200, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', status: 'active', inStock: true, quantity: 85, lastUpdated: '5h ago' },
      { warehouse: 'Ras Al Khaimah', status: 'retired', inStock: false, quantity: 0, lastUpdated: '1d ago' },
    ],
  },
  {
    skuId: 'TB-AE-009',
    name: 'Red Bull 250ml',
    category: 'Beverages',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 4.90,
    basePrice: 7.00,
    discount: null,
    margin: 30,
    engineSignals: ['profitability'],
    supplier: 'Red Bull',
    weeklyUnitsSold: 1456,
    availability: 97,
    warehouses: [
      { warehouse: 'Dubai Central', status: 'active', inStock: true, quantity: 520, lastUpdated: '1h ago' },
      { warehouse: 'Abu Dhabi Hub', status: 'active', inStock: true, quantity: 380, lastUpdated: '2h ago' },
      { warehouse: 'Sharjah DC', status: 'active', inStock: true, quantity: 290, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', status: 'active', inStock: true, quantity: 180, lastUpdated: '5h ago' },
      { warehouse: 'Ras Al Khaimah', status: 'active', inStock: true, quantity: 120, lastUpdated: '6h ago' },
    ],
  },
  {
    skuId: 'TB-AE-010',
    name: 'Coca-Cola 330ml Can',
    category: 'Beverages',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 2.28,
    basePrice: 3.25,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Coca-Cola',
    weeklyUnitsSold: 2800,
    availability: 99,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 1800, lastUpdated: '45m ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 1200, lastUpdated: '1h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 950, lastUpdated: '2h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 600, lastUpdated: '3h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: true, quantity: 400, lastUpdated: '4h ago' },
    ],
  },
  {
    skuId: 'TB-AE-011',
    name: 'Pepsi 330ml Can',
    category: 'Beverages',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 2.10,
    basePrice: 3.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'PepsiCo',
    weeklyUnitsSold: 2450,
    availability: 98,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 1500, lastUpdated: '1h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 1100, lastUpdated: '2h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 850, lastUpdated: '3h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 520, lastUpdated: '4h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: true, quantity: 380, lastUpdated: '5h ago' },
    ],
  },
  {
    skuId: 'TB-AE-012',
    name: 'Mountain Dew 500ml',
    category: 'Beverages',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 2.80,
    basePrice: 4.00,
    discount: null,
    margin: 30,
    engineSignals: ['profitability'],
    supplier: 'PepsiCo',
    weeklyUnitsSold: 1680,
    availability: 96,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 620, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 480, lastUpdated: '3h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 320, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 180, lastUpdated: '5h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: true, quantity: 85, lastUpdated: '6h ago' },
    ],
  },

  // === SNACKS & CHOCOLATE ===
  {
    skuId: 'TB-AE-013',
    name: 'Cadbury Dairy Milk 45g',
    category: 'Snacks & Chocolate',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 3.50,
    basePrice: 5.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Mondelez',
    weeklyUnitsSold: 2100,
    availability: 98,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 720, lastUpdated: '1h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 540, lastUpdated: '2h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 400, lastUpdated: '3h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 280, lastUpdated: '4h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: true, quantity: 160, lastUpdated: '5h ago' },
    ],
  },
  {
    skuId: 'TB-AE-014',
    name: 'Lays Classic Chips 150g',
    category: 'Snacks & Chocolate',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 4.90,
    basePrice: 7.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'PepsiCo',
    weeklyUnitsSold: 1920,
    availability: 97,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 680, lastUpdated: '1h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 490, lastUpdated: '2h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 360, lastUpdated: '3h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 220, lastUpdated: '4h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '12h ago' },
    ],
  },
  {
    skuId: 'TB-AE-015',
    name: 'Kinder Chocolate 100g',
    category: 'Snacks & Chocolate',
    status: 'active',
    maturityStage: 'probation',
    efficiency: 'efficient',
    costPrice: 7.00,
    basePrice: 10.00,
    discount: null,
    margin: 30,
    engineSignals: ['lifecycle'],
    supplier: 'Ferrero',
    weeklyUnitsSold: 780,
    availability: 91,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 290, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 220, lastUpdated: '3h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 150, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '1d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '1d ago' },
    ],
  },
  {
    skuId: 'TB-AE-016',
    name: 'Galaxy Chocolate 45g',
    category: 'Snacks & Chocolate',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 3.50,
    basePrice: 5.00,
    discount: 5,
    margin: 30,
    engineSignals: [],
    supplier: 'Mars',
    weeklyUnitsSold: 1650,
    availability: 95,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 580, lastUpdated: '1h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 420, lastUpdated: '2h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 310, lastUpdated: '3h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 180, lastUpdated: '4h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: true, quantity: 95, lastUpdated: '5h ago' },
    ],
  },
  {
    skuId: 'TB-AE-017',
    name: 'Pringles Original 110g',
    category: 'Snacks & Chocolate',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 5.60,
    basePrice: 8.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Kelloggs',
    weeklyUnitsSold: 1240,
    availability: 94,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 450, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 320, lastUpdated: '3h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 210, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 120, lastUpdated: '5h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '1d ago' },
    ],
  },
  {
    skuId: 'TB-AE-018',
    name: 'Doritos Nacho Cheese 150g',
    category: 'Snacks & Chocolate',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 5.25,
    basePrice: 7.50,
    discount: null,
    margin: 30,
    engineSignals: ['profitability'],
    supplier: 'PepsiCo',
    weeklyUnitsSold: 1380,
    availability: 96,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 510, lastUpdated: '1h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 380, lastUpdated: '2h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 250, lastUpdated: '3h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 140, lastUpdated: '4h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: true, quantity: 80, lastUpdated: '5h ago' },
    ],
  },

  // === PERSONAL CARE ===
  {
    skuId: 'TB-AE-019',
    name: 'Dove Body Lotion 400ml',
    category: 'Personal Care',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 14.00,
    basePrice: 20.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Unilever',
    weeklyUnitsSold: 420,
    availability: 88,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 160, lastUpdated: '3h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 120, lastUpdated: '4h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 75, lastUpdated: '5h ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '2d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '2d ago' },
    ],
  },
  {
    skuId: 'TB-AE-020',
    name: 'Colgate Toothpaste 100ml',
    category: 'Personal Care',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 5.25,
    basePrice: 7.50,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Colgate-Palmolive',
    weeklyUnitsSold: 890,
    availability: 94,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 340, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 250, lastUpdated: '3h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 170, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 90, lastUpdated: '5h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '1d ago' },
    ],
  },
  {
    skuId: 'TB-AE-021',
    name: 'Head & Shoulders Shampoo 400ml',
    category: 'Personal Care',
    status: 'active',
    maturityStage: 'review',
    efficiency: 'slow-mover',
    costPrice: 14.00,
    basePrice: 20.00,
    discount: 15,
    margin: 35,
    engineSignals: ['lifecycle', 'affordability'],
    supplier: 'P&G',
    weeklyUnitsSold: 320,
    availability: 82,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 120, lastUpdated: '4h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 95, lastUpdated: '5h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 55, lastUpdated: '6h ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '3d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '3d ago' },
    ],
  },
  {
    skuId: 'TB-AE-022',
    name: 'Nivea Body Cream 250ml',
    category: 'Personal Care',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 10.50,
    basePrice: 15.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Nivea',
    weeklyUnitsSold: 580,
    availability: 90,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 220, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 160, lastUpdated: '3h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 110, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '1d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '2d ago' },
    ],
  },

  // === HOUSEHOLD ===
  {
    skuId: 'TB-AE-023',
    name: 'Ariel Detergent 3kg',
    category: 'Household',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 24.50,
    basePrice: 35.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'P&G',
    weeklyUnitsSold: 380,
    availability: 85,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 145, lastUpdated: '3h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 110, lastUpdated: '4h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 70, lastUpdated: '5h ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '2d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '2d ago' },
    ],
  },
  {
    skuId: 'TB-AE-024',
    name: 'Tide Detergent 2kg',
    category: 'Household',
    status: 'active',
    maturityStage: 'probation',
    efficiency: 'efficient',
    costPrice: 17.50,
    basePrice: 25.00,
    discount: null,
    margin: 30,
    engineSignals: ['lifecycle'],
    supplier: 'P&G',
    weeklyUnitsSold: 290,
    availability: 88,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 110, lastUpdated: '4h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 85, lastUpdated: '5h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 50, lastUpdated: '6h ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '2d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '3d ago' },
    ],
  },
  {
    skuId: 'TB-AE-025',
    name: 'Clorox Bleach 1L',
    category: 'Household',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 3.50,
    basePrice: 5.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Clorox',
    weeklyUnitsSold: 720,
    availability: 92,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 280, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 200, lastUpdated: '3h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 140, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 70, lastUpdated: '5h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '1d ago' },
    ],
  },

  // === FROZEN FOODS ===
  {
    skuId: 'TB-AE-026',
    name: 'Frozen Chicken Nuggets 500g',
    category: 'Frozen Foods',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 14.00,
    basePrice: 20.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'McCain',
    weeklyUnitsSold: 580,
    availability: 90,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 220, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 160, lastUpdated: '3h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 110, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '1d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '2d ago' },
    ],
  },
  {
    skuId: 'TB-AE-027',
    name: 'Frozen Peas 500g',
    category: 'Frozen Foods',
    status: 'active',
    maturityStage: 'mature',
    efficiency: 'efficient',
    costPrice: 3.50,
    basePrice: 5.00,
    discount: null,
    margin: 30,
    engineSignals: [],
    supplier: 'Al Kabeer',
    weeklyUnitsSold: 680,
    availability: 93,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 260, lastUpdated: '2h ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 190, lastUpdated: '3h ago' },
      { warehouse: 'Sharjah DC', inStock: true, quantity: 130, lastUpdated: '4h ago' },
      { warehouse: 'Ajman Warehouse', inStock: true, quantity: 65, lastUpdated: '5h ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '1d ago' },
    ],
  },

  // === ON-HOLD SKUs - Need Review ===
  {
    skuId: 'TB-AE-028',
    name: 'Organic Almond Milk 1L',
    category: 'Dairy & Cheese',
    status: 'on-hold',
    maturityStage: 'review',
    efficiency: 'slow-mover',
    costPrice: 14.00,
    basePrice: 20.00,
    discount: null,
    margin: 30,
    engineSignals: ['lifecycle'],
    supplier: 'Blue Diamond',
    weeklyUnitsSold: 45,
    availability: 72,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 85, lastUpdated: '1d ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: false, quantity: 0, lastUpdated: '3d ago' },
      { warehouse: 'Sharjah DC', inStock: false, quantity: 0, lastUpdated: '5d ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '7d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '7d ago' },
    ],
  },
  {
    skuId: 'TB-AE-029',
    name: 'Premium Saffron 1g',
    category: 'Spices',
    status: 'on-hold',
    maturityStage: 'review',
    efficiency: 'slow-mover',
    costPrice: 28.00,
    basePrice: 40.00,
    discount: null,
    margin: 30,
    engineSignals: ['profitability'],
    supplier: 'Spanish Saffron Co',
    weeklyUnitsSold: 12,
    availability: 65,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 25, lastUpdated: '2d ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 15, lastUpdated: '3d ago' },
      { warehouse: 'Sharjah DC', inStock: false, quantity: 0, lastUpdated: '7d ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '14d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '14d ago' },
    ],
  },
  {
    skuId: 'TB-AE-030',
    name: 'Imported Olive Oil 500ml',
    category: 'Cooking Ingredients',
    status: 'on-hold',
    maturityStage: 'probation',
    efficiency: 'slow-mover',
    costPrice: 21.00,
    basePrice: 30.00,
    discount: null,
    margin: 30,
    engineSignals: ['affordability'],
    supplier: 'Bertolli',
    weeklyUnitsSold: 85,
    availability: 78,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 45, lastUpdated: '1d ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 30, lastUpdated: '2d ago' },
      { warehouse: 'Sharjah DC', inStock: false, quantity: 0, lastUpdated: '5d ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '7d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '10d ago' },
    ],
  },

  // === DISCONTINUED SKUs - Being Phased Out ===
  {
    skuId: 'TB-AE-031',
    name: 'Local Brand Chips 100g',
    category: 'Snacks',
    status: 'discontinued',
    maturityStage: 'phase-out',
    efficiency: 'zero-mover',
    costPrice: 2.80,
    basePrice: 4.00,
    discount: 50,
    margin: 30,
    engineSignals: ['lifecycle'],
    supplier: 'Local Foods LLC',
    weeklyUnitsSold: 8,
    availability: 35,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 42, lastUpdated: '3d ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: false, quantity: 0, lastUpdated: '7d ago' },
      { warehouse: 'Sharjah DC', inStock: false, quantity: 0, lastUpdated: '10d ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '14d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '14d ago' },
    ],
  },
  {
    skuId: 'TB-AE-032',
    name: 'Generic Soap Bar',
    category: 'Personal Care',
    status: 'discontinued',
    maturityStage: 'phase-out',
    efficiency: 'zero-mover',
    costPrice: 1.40,
    basePrice: 2.00,
    discount: 30,
    margin: 30,
    engineSignals: [],
    supplier: 'Generic Brands Inc',
    weeklyUnitsSold: 5,
    availability: 28,
    warehouses: [
      { warehouse: 'Dubai Central', inStock: true, quantity: 18, lastUpdated: '5d ago' },
      { warehouse: 'Abu Dhabi Hub', inStock: true, quantity: 12, lastUpdated: '7d ago' },
      { warehouse: 'Sharjah DC', inStock: false, quantity: 0, lastUpdated: '14d ago' },
      { warehouse: 'Ajman Warehouse', inStock: false, quantity: 0, lastUpdated: '14d ago' },
      { warehouse: 'Ras Al Khaimah', inStock: false, quantity: 0, lastUpdated: '14d ago' },
    ],
  },
];

// Filtered SKUs - only those with sales or stock (relevant for category managers)
export const RELEVANT_SKUS = SAMPLE_SKUS.filter(sku =>
  sku.weeklyUnitsSold > 0 || sku.warehouses.some(w => w.inStock && w.quantity > 0)
);

// Sample Assortment Recommendations
export const SAMPLE_ASSORTMENT_RECS = [
  {
    source: 'competitor' as const,
    skuName: 'Sadia Choc Milk 200ml',
    rationale: 'Listed on Carrefour & Noon at AED 3.50. Ranked #4 in Dairy search. Est. 800+ units/month.',
    confidence: 91,
  },
  {
    source: 'search' as const,
    skuName: 'Oat milk 1L',
    rationale: 'Search volume up 340% MoM in UAE. Zero coverage in category. Price potential AED 18–24.',
    confidence: 85,
  },
  {
    source: 'nielsen' as const,
    skuName: 'Nadec Full Cream 2L',
    rationale: 'Top 3 nationally by unit sales in MT channel. Not listed on Talabat. Margin est. 28–32%.',
    confidence: 78,
  },
];

// DH Entities
export const DH_ENTITIES = [
  'Talabat UAE',
  'Talabat Kuwait',
  'Talabat Egypt',
  'Hunger Station',
  'Pandora',
  'Pedidos Ya',
  'MXFAD',
];

// Categories
export const CATEGORIES = [
  { name: 'All Categories', path: '/' },
  { name: 'Beverages & Dairy', path: '/beverages-dairy' },
  { name: 'Snacks & Confectionery', path: '/snacks' },
  { name: 'Fresh & Frozen', path: '/fresh-frozen' },
  { name: 'Grocery & Staples', path: '/grocery' },
];

// Real UAE Store Performance from BigQuery
export const UAE_STORES = [
  { name: 'UAE_Dubai_DS_21 - Shamkha, Abu Dhabi', orders: 95030, gmv: 1846129 },
  { name: 'UAE_Dubai_DS_6 - JVC', orders: 49731, gmv: 897010 },
  { name: 'UAE_Dubai_DS_38_Mussafah', orders: 45079, gmv: 876397 },
  { name: 'UAE_Dubai_DS_16_Al Jurf', orders: 39368, gmv: 668810 },
  { name: 'UAE_Dubai_DS_35_Palm Jumeirah', orders: 41482, gmv: 850542 },
  { name: 'UAE_Dubai_DS_3 - Motor City', orders: 41879, gmv: 807306 },
  { name: 'UAE_Dubai_DS_29 - Zone One', orders: 45216, gmv: 830811 },
  { name: 'UAE_Dubai_DS_13 - Khalifa (Abu Dhabi)', orders: 45858, gmv: 837366 },
];

// UAE GMV Trend (from BigQuery)
export const UAE_GMV_TREND = [
  { month: 'Nov 2025', gmv: 30780233, orders: 1627151 },
  { month: 'Dec 2025', gmv: 29535086, orders: 1586401 },
  { month: 'Jan 2026', gmv: 31518281, orders: 1684626 },
];